class LanguageService {
  String language;
  Map<String, String> dictionary;

  LanguageService({required this.language, this.dictionary = const <String, String>{}});

  static LanguageService getInstance(String language) {
    LanguageService lang = LanguageService(language: language, dictionary: readJsonFile(language)); // TODO: read from JSON file
    return lang;
  }

  String translate(String key) {
    if (dictionary.containsKey(key)) return dictionary[key]!;
    return "";
  }

  static Map<String, String> readJsonFile(String language) {
    switch (language) {
      case "en":
        final jsonEN = {
          "project_title": "Graduation thesis",
          "users": "Users",
          "estates": "Estates",
          "profile_page": "Profile page",
          "change_password": "Change password",
          "delete_account": "Delete account",
          "sign_out": "Sign out",
          "loading": "Loading",
          "save_changes": "Save changes",
          "personal_information": "Personal information",
          "your_address": "Your address",
          "preferences": "Preferences",
          "obtaining_user_information":
              "Obtaining your information. Please wait.",
          "firstname": "First name",
          "owner_firstname": "Owner's first name",
          "lastname": "Last name",
          "owner_lastname": "Owner's last name",
          "date_of_birth": "Date of birth",
          "company_name": "Company's name",
          "phone_number": "Phone number",
          "street": "Street",
          "zip": "Zip",
          "city": "City",
          "country": "Country",
          "distance_units": "Distance units",
          "km": "Kilometers",
          "mi": "Miles",
          "temperature_units": "Temperature units",
          "date_formats": "Date formats",
          "en": "English",
          "de": "German",
          "hr": "Croatian",
          "language": "Language",
          "account_successfully_updated":
              "Your account has successfully been updated!",
          "dismiss": "Dismiss",
          "error_while_updating_user": "There was an error while updating your account.",
          "profile_image": "Profile image",
          "background_image": "Background image",
          "discard_image": "Discard image",
          "dropzone_text": "Drop images here or browse through files",
          "no_estates": "There are no estates to display!",
          "list": "List",
          "map": "Map",
          "manage_presentation": "Manage presentation",
          "general_information": "General information",
          "additional_information": "Additional information",
          "description": "Description",
          "create_estate": "Create estate",
          "add_new_estate": "Add a new estate",
          "search_text":
              "Here you can search for names, emails and phone numbers",
          "additional_filters": "Additional filters",
          "number_of_estates": "Number of estates",
          "from": "From",
          "from_date": "Arrival date",
          "from_time": "Arrival time",
          "to": "To",
          "to_date": "Departure date",
          "to_time": "Departure time",
          "blocked": "Blocked",
          "individual": "Individual",
          "banned": "Banned",
          "company": "Company",
          "apply_filters": "Apply filters",
          "image": "Image",
          "name": "Name",
          "type": "Type",
          "users_per_page": "Users per page",
          "scroll_to_top": "Scroll to top",
          "allow_pets": "Allow pets",
          "allow_smoking": "Allow smoking",
          "air_conditioning": "Air conditioning",
          "handicap_accessible": "Handicap accessible",
          "designated_parking_spots": "Designated parking spots",
          "outlet_type": "Outlet type",
          "house_orientation": "House orientation",
          "accepting_payment_cards": "Accepting payment cards",
          "wifi": "Wifi",
          "pool": "Pool",
          "kitchen": "Kitchen",
          "washing_machine": "Washing machine",
          "drying_machine": "Drying machine",
          "edit_presentation": "Edit presentation",
          "delete_estate": "Delete estate",
          "delete_estate_warning_message": "Are you sure you want to delete your estate?",
          "cancel": "Cancel",
          "choose_file": "Choose file",
          "no_file": "No file",
          "cannot_preview": "Cannot preview",
          "save_image": "Save image",
          "banned_by_admin":
              "Your account has been banned by the admin. You can contact the admin at admin@diplomski.com for more information.",
          "blocked_by_admin":
              "Your account is currently blocked by the admin. You can contact the admin at admin@diplomski.com for more information.",
          "cant_log_in": "There was an error while logging in.",
          "successful_login": "You have successfully logged in!",
          "sign_up": "Sign up",
          "type_of_customer": "Type of customer",
          "password": "Password",
          "repeat_password": "Repeat password",
          "keep_me_logged_in": "Keep me logged in.",
          "have_account_login_here": "Already have an account? Sign in here.",
          "cant_register":
              "There is a problem while trying to create your account. Please try again later.",
          "account_successfully_created":
              "Your account has successfully been created!",
          "dont_have_account_register_here":
              "Don't have an account? Sign up here.",
          "sign_in": "Sign in",
          "sign_in_with_google": "Sign in with Google",
          "sign_in_with_facebook": "Sign in with Facebook",
          "customers": "Customers",
          "old_password": "Old password",
          "new_password": "New password",
          "delete_account_warning_message":
              "Are you sure you want to delete your account? Your data will be permanently lost!",
          "avatar_image": "Avatar image",
          "or": "or",
          "email": "Email",
          "show": "Show",
          "dont_show": "Don't show",
          "slides": "Slides",
          "title": "Title",
          "subtitle": "Subtitle",
          "drop_image_here": "Drop image here!",
          "template": "Template",
          "successfull_delete_account": "You successfully deleted your account!",
          "add_next_slide": "Add slide as next",
          "delete_slide": "Delete slide",
          "add_prev_slide": "Add slide as previous",
          "key": "Abbreviation",
          "value": "Text",
          "variables": "Variables",
          "no_elements": "There is nothing to display!",
          "position": "Position",
          "title_text": "Title text",
          "title_alignment": "Title alignment",
          "top-left": "Top left",
          "top-center": "Top center",
          "top-right": "Top right",
          "center": "Center",
          "links": "Links",
          "link": "Link",
          "links_text": "Links text",
          "links_url": "Links url",
          "background": "Background",
          "images": "Images",
          "open_gallery": "Open gallery",
          "text": "Text",
          "description_text": "Description text",
          "add_category": "Add category",
          "name_en": "Name in English",
          "name_de": "Name in German",
          "name_hr": "Name in Croatian",
          "title_en": "Title in English",
          "title_de": "Title in German",
          "title_hr": "Title in Croatian",
          "description_en": "Description in English",
          "description_de": "Description in German",
          "description_hr": "Description in Croatian",
          "guests": "Guests",
          "set_date": "Set date",
          "set_time": "Set time",
          "titles": "Titles",
          "cant_obtain_estates": "There was an error while trying to obtain your estates. Please try again later.",
          "cant_obtain_categories": "There was an error while trying to obtain your categories. Please try again later.",
          "cant_obtain_elements": "There was an error while trying to obtain your items. Please try again later.",
          "must_save_or_cancel_changes": "Before leaving to another item, you must save or cancel all the changes.",
          "create_element": "Create item",
          "delete_element": "Delete item",
          "update_element": "Update item",
          "passwords_do_not_match": "Passwords do not match.",
          "fill_all_requested_fields": "Please fill all requested field to continue with the registration process.",
          "old_password_does_not_match": "You entered the wrong old password!",
          "error_while_updating_password": "There was an error while updating your password.",
          "successfull_changed_password": "Your password has successfully been updated.",
          "error_while_gathering_your_data": "There was an error while gathering your data.",
          "error_while_deleting_account": "There was an error while deleting your account. Please try again later.",
          "complete": "Complete",
          "compact": "Compact",
          "minimal": "Minimal",
          "entry_fee": "Entrance fee",
          "minimal_age": "Minimal age",
          "monday": "Monday",
          "tuesday": "Tuesday",
          "wednesday": "Wednesday",
          "thursday": "Thursday",
          "friday": "Friday",
          "saturday": "Saturday",
          "sunday": "Sunday",
          "manage_category": "Manage category",
          "manage_elements": "Manage items",
          "show_elements": "Show items",
          "show_category": "Show category",
          "ban_user_text_1": "Are you sure you want to ban ",
          "ban_user_text_2": "? Banishment of any user is permanent and will erase their information from the database!",
          "working_hours": "Working hours",
          "opening_hour": "Opening hours",
          "closing_hour": "Closing hours",
          "delete_element_warning_message": "Are you sure you want to delete your item?",
          "first_column_must_be_filled": "In order to proceed with the save, you must enter all values in the first (left) column!",
          "new_password_too_short": "The new password is too short! It must have at least 8 characters.",
          "all_general_info_has_to_be_filled": "All \"General info\" fields have to be filled!",
          "all_guest_info_has_to_be_filled": "Every created row in \"Guests\" section must be filled!",
          "you_must_enter_all_names": "To proceed, you must enter all names!",
          "cannot_update_estate": "There was an error while updating estates.",
          "estate_successfully_updated": "Estate was successfully updated.",
          "category_successfully_updated": "Category successfully updated!",
          "error_while_updating_category": "There was an error updating your category.",
          "category_successfully_created": "Category successfully created!",
          "error_while_creating_category": "There was an error creating your category.",
          "delete_category": "Delete category",
          "cannot_create_estate": "There was an error while creating your estate.",
          "estate_successfully_created": "Your estate was successfully created.",
          "pick_file": "Pick file",
          "estate_successfully_deleted": "Estate successfully deleted!",
          "error_while_deleting_estate": "There was an error deleting your estate.",
          "error_while_deleting_category": "There was an error while deleting your category.",
          "category_successfully_deleted": "Category successfully deleted!",
          "error_while_updating_element": "There was an error while updating your item.",
          "element_successfully_updated": "Element successfully updated!",
          "error_while_deleting_element": "There was an error while deleting your item.",
          "element_successfully_deleted": "Element successfully deleted!",
          "error_while_creating_element": "There was an error while creating your item.",
          "element_successfully_created": "Item successfully created!",
          "no_users_to_display": "No users to display",
        };
        return jsonEN;
      case "de":
        final jsonDE = {
          "project_title": "Abschlussarbeit",
          "users": "Benutzer",
          "estates": "Immobilien",
          "profile_page": "Profilseite",
          "change_password": "Passwort ändern",
          "delete_account": "Konto löschen",
          "sign_out": "Abmelden",
          "loading": "Wird geladen",
          "save_changes": "Änderungen speichern",
          "personal_information": "Persönliche Angaben",
          "your_address": "Deine Adresse",
          "preferences": "Präferenzen",
          "obtaining_user_information":
              "Einholen Ihrer Informationen. Bitte warten.",
          "firstname": "Vorname",
          "owner_firstname": "Vorname des Besitzers",
          "lastname": "Nachname",
          "owner_lastname": "Nachname des Besitzers",
          "date_of_birth": "Geburtsdatum",
          "company_name": "Firmenname",
          "phone_number": "Telefonnummer",
          "street": "Straße",
          "zip": "Reißverschluss",
          "city": "Stadt",
          "country": "Land",
          "distance_units": "Entfernungseinheiten",
          "km": "Kilometer",
          "mi": "Meilen",
          "temperature_units": "Temperatureinheiten",
          "date_formats": "Datumsformate",
          "en": "Englisch",
          "de": "Deutsch",
          "hr": "Kroatische",
          "language": "Sprache",
          "account_successfully_updated":
              "Ihr Konto wurde erfolgreich aktualisiert!",
          "dismiss": "Zurückweisen",
          "error_while_updating_user": "Beim Aktualisieren Ihres Kontos ist ein Fehler aufgetreten.",
          "profile_image": "Profilbild",
          "background_image": "Hintergrundbild",
          "discard_image": "Bild verwerfen",
          "dropzone_text":
              "Legen Sie hier Bilder ab oder durchsuchen Sie die Dateien",
          "no_estates": "Es sind keine Immobilien zum Anzeigen vorhanden!",
          "list": "Aufführen",
          "map": "Karte",
          "manage_presentation": "Präsentation verwalten",
          "general_information": "Allgemeine Informationen",
          "additional_information": "Weitere Informationen",
          "description": "Beschreibung",
          "create_estate": "Immobilien schaffen",
          "add_new_estate": "Fügen Sie eine neue Immobilie hinzu",
          "search_text":
              "Hier können Sie nach Namen, E-Mails und Telefonnummern suchen",
          "additional_filters": "Zusätzliche Filter",
          "number_of_estates": "Anzahl der Nachlässe",
          "from": "Aus",
          "from_date": "Datum der Ankunft",
          "from_time": "Ankunftszeit",
          "to": "Zu",
          "to_date": "Abreisedatum",
          "to_time": "Abfahrtszeit",
          "blocked": "Verstopft",
          "individual": "Individuell",
          "banned": "Verboten",
          "company": "Unternehmen",
          "apply_filters": "Wenden Sie Filter an",
          "image": "Bild",
          "name": "Name",
          "type": "Typ",
          "users_per_page": "Benutzer pro Seite",
          "scroll_to_top": "Nach oben scrollen",
          "allow_pets": "Haustiere sind erlaubt",
          "allow_smoking": "Rauchen erlauben",
          "air_conditioning": "Klimaanlage",
          "handicap_accessible": "Behindertengerecht",
          "designated_parking_spots": "Ausgewiesene Parkplätze",
          "outlet_type": "Steckdosentyp",
          "house_orientation": "Hausorientierung",
          "accepting_payment_cards": "Akzeptieren von Zahlungskarten",
          "wifi": "Wifi",
          "pool": "Schwimmbad",
          "kitchen": "Küche",
          "washing_machine": "Waschmaschine",
          "drying_machine": "Trockner",
          "edit_presentation": "Präsentation bearbeiten",
          "delete_estate": "Immobilien löschen",
          "delete_estate_warning_message":
              "Sind Sie sicher, dass Sie Ihre Immobilie löschen möchten?",
          "cancel": "Abbrechen",
          "choose_file": "Datei wählen",
          "no_file": "Keine datei",
          "cannot_preview": "Vorschau nicht möglich",
          "save_image": "Bild speichern",
          "banned_by_admin":
              "Ihr Konto wurde vom Administrator gesperrt. Für weitere Informationen können Sie den Administrator unter admin@diplomski.com kontaktieren.",
          "blocked_by_admin":
              "Ihr Konto ist derzeit vom Administrator gesperrt. Für weitere Informationen können Sie den Administrator unter admin@diplomski.com kontaktieren.",
          "cant_log_in": "Beim Anmelden ist ein Fehler aufgetreten.",
          "successful_login": "Sie haben sich erfolgreich angemeldet!",
          "customers": "Kunden",
          "old_password": "Altes Passwort",
          "new_password": "Neue Passwort",
          "repeat_password": "Passwort wiederholen",
          "type_of_customer": "Kundentyp",
          "password": "Passwort",
          "delete_account_warning_message":
              "Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Ihre Daten gehen dauerhaft verloren!",
          "sign_up": "Anmelden",
          "have_account_login_here":
              "Haben Sie bereits ein Konto? Melden Sie sich hier an.",
          "keep_me_logged_in": "Eingeloggt bleiben.",
          "cant_register":
              "Beim Versuch, Ihr Konto zu erstellen, ist ein Problem aufgetreten. Bitte versuchen Sie es später erneut.",
          "account_successfully_created":
              "Ihr Konto wurde erfolgreich erstellt!",
          "dont_have_account_register_here":
              "Sie haben noch kein Konto? Melden Sie sich hier an.",
          "sign_in": "Anmelden",
          "sign_in_with_google": "Mit Google anmelden",
          "sign_in_with_facebook": "Mit Facebook anmelden",
          "avatar_image": "Profilbild",
          "or": "oder",
          "email": "Email",
          "show": "Zeigen",
          "dont_show": "Nicht zeigen",
          "slides": "Folien",
          "title": "Titel",
          "subtitle": "Untertitel",
          "drop_image_here": "Bild hier einfügen!",
          "template": "Vorlage",
          "successfull_delete_account":
              "Sie haben Ihr Konto erfolgreich gelöscht!",
          "add_next_slide": "Als nächstes Folie hinzufügen",
          "delete_slide": "Folie löschen",
          "add_prev_slide": "Folie wie zuvor hinzufügen",
          "key": "Abkürzung",
          "value": "Text",
          "variables": "Variablen",
          "no_elements": "Es gibt nichts anzuzeigen!",
          "position": "Position",
          "title_text": "Titeltext",
          "title_alignment": "Titelausrichtung",
          "top-left": "Oben links",
          "top-center": "Oben in der Mitte",
          "top-right": "Oben rechts",
          "center": "Center",
          "links": "Links",
          "link": "Link",
          "links_text": "Linktext",
          "links_url": "Link-URL",
          "background": "Hintergrund",
          "images": "Bilder",
          "open_gallery": "Galerie öffnen",
          "text": "Text",
          "description_text": "Beschreibungstext",
          "add_category": "Kategorie hinzufügen",
          "name_en": "Name auf Englisch",
          "name_de": "Name auf Deutsch",
          "name_hr": "Name auf Kroatisch",
          "title_en": "Titel auf Englisch",
          "title_de": "Titel auf Deutsch",
          "title_hr": "Titel auf Kroatisch",
          "description_en": "Beschreibung auf Englisch",
          "description_de": "Beschreibung auf Deutsch",
          "description_hr": "Beschreibung auf Kroatisch",
          "guests": "Gäste",
          "set_date": "Datum einstellen",
          "set_time": "Zeit einstellen",
          "titles": "Titel",
          "cant_obtain_estates": "Beim Versuch, Ihre Nachlässe zu erhalten, ist ein Fehler aufgetreten. Bitte versuchen Sie es später noch einmal.",
          "cant_obtain_categories": "Beim Versuch, Ihre Kategorien abzurufen, ist ein Fehler aufgetreten. Bitte versuchen Sie es später noch einmal.",
          "cant_obtain_elements": "Beim Abrufen Ihrer Artikel ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
          "must_save_or_cancel_changes": "Bevor Sie zu einem anderen Element wechseln, müssen Sie alle Änderungen speichern oder verwerfen.",
          "create_element": "Artikel erstellen",
          "delete_element": "Artikel löschen",
          "update_element": "Artikel aktualisieren",
          "passwords_do_not_match": "Passwörter stimmen nicht überein.",
          "fill_all_requested_fields": "Bitte füllen Sie alle erforderlichen Felder aus, um mit dem Registrierungsprozess fortzufahren.",
          "old_password_does_not_match": "Sie haben das falsche alte Passwort eingegeben!",
          "error_while_updating_password": "Beim Aktualisieren Ihres Passworts ist ein Fehler aufgetreten.",
          "successfull_changed_password": "Ihr Passwort wurde erfolgreich aktualisiert.",
          "error_while_gathering_your_data": "Beim Sammeln Ihrer Daten ist ein Fehler aufgetreten.",
          "error_while_deleting_account": "Beim Löschen Ihres Kontos ist ein Fehler aufgetreten. Bitte versuchen Sie es später noch einmal.",
          "complete": "Vollständig",
          "compact": "Kompakt",
          "minimal": "Minimal",
          "entry_fee": "Eintrittspreis",
          "minimal_age": "Mindestalter",
          "monday": "Montag",
          "tuesday": "Dienstag",
          "wednesday": "Mittwoch",
          "thursday": "Donnerstag",
          "friday": "Freitag",
          "saturday": "Samstag",
          "sunday": "Sonntag",
          "manage_category": "Kategorie verwalten",
          "manage_elements": "Verwalten von Elementen",
          "show_elements": "Artikel anzeigen",
          "show_category": "Kategorie anzeigen",
          "ban_user_text_1": "Möchten Sie wirklich sperren?",
          "ban_user_text_2": "? Die Sperrung eines Benutzers ist dauerhaft und löscht seine Informationen aus der Datenbank!",
          "working_hours": "Arbeitszeit",
          "opening_hour": "Öffnungszeiten",
          "closing_hour": "Schließungszeiten",
          "delete_element_warning_message": "Sind Sie sicher, dass Sie Ihr Element löschen möchten?",
          "first_column_must_be_filled": "Um mit dem Speichern fortzufahren, müssen Sie alle Werte in die erste (links) Spalte eingeben!",
          "new_password_too_short": "Das neue Passwort ist zu kurz! Es muss mindestens 8 Zeichen lang sein.",
          "all_general_info_has_to_be_filled": "Alle \"Allgemeine Informationen\" Felder müssen ausgefüllt werden!",
          "all_guest_info_has_to_be_filled": "Jede erstellte Zeile im Abschnitt \"Gäste\" muss ausgefüllt werden!",
          "you_must_enter_all_names": "Um fortzufahren, müssen Sie alle Namen eingeben!",
          "cannot_update_estate": "Beim Aktualisieren der Anwesen ist ein Fehler aufgetreten.",
          "estate_successfully_updated": "Der Nachlass wurde erfolgreich aktualisiert.",
          "category_successfully_updated": "Kategorie erfolgreich aktualisiert!",
          "error_while_updating_category": "Beim Aktualisieren Ihrer Kategorie ist ein Fehler aufgetreten.",
          "category_successfully_created": "Kategorie erfolgreich erstellt!",
          "error_while_creating_category": "Beim Erstellen Ihrer Kategorie ist ein Fehler aufgetreten.",
          "delete_category": "Kategorie löschen",
          "cannot_create_estate": "Beim Erstellen Ihres Nachlasses ist ein Fehler aufgetreten.",
          "estate_successfully_created": "Ihre Immobilie wurde erfolgreich angelegt.",
          "pick_file": "Datei auswählen",
          "estate_successfully_deleted": "Immobilie erfolgreich gelöscht!",
          "error_while_deleting_estate": "Beim Löschen Ihres Immobilie ist ein Fehler aufgetreten.",
          "error_while_deleting_category": "Beim Löschen Ihrer Kategorie ist ein Fehler aufgetreten.",
          "category_successfully_deleted": "Kategorie erfolgreich gelöscht!",
          "error_while_updating_element": "Beim Aktualisieren Ihres Artikels ist ein Fehler aufgetreten.",
          "element_successfully_updated": "Element erfolgreich aktualisiert!",
          "error_while_deleting_element": "Beim Löschen Ihres Artikels ist ein Fehler aufgetreten.",
          "element_successfully_deleted": "Element erfolgreich gelöscht!",
          "error_while_creating_element": "Beim Erstellen Ihres Artikels ist ein Fehler aufgetreten.",
          "element_successfully_created": "Artikel erfolgreich erstellt!",
          "no_users_to_display": "Keine Benutzer zum Anzeigen",
        };
        return jsonDE;
      case "hr":
        final jsonHR = {
          "project_title": "Diplomski rad",
          "users": "Korisnici",
          "estates": "Nekretnine",
          "profile_page": "Stranica profila",
          "change_password": "Promijeni lozinku",
          "delete_account": "Izbriši račun",
          "sign_out": "Odjavi se",
          "loading": "Učitavanje",
          "save_changes": "Spremi izmjene",
          "personal_information": "Osobni podatci",
          "your_address": "Vaša adresa",
          "preferences": "Postavke",
          "obtaining_user_information":
              "Dobivanje vaših podataka. Molimo pričekajte.",
          "firstname": "Ime",
          "owner_firstname": "Ime vlasnika",
          "lastname": "Prezime",
          "owner_lastname": "Prezime vlasnika",
          "date_of_birth": "Datum rođenja",
          "company_name": "Naziv tvrtke",
          "phone_number": "Broj telefona",
          "street": "Ulica",
          "zip": "Poštanski broj",
          "city": "Grad",
          "country": "Država",
          "distance_units": "Jedinice udaljenosti",
          "km": "Kilometri",
          "mi": "Milje",
          "temperature_units": "Jedinice za temperaturu",
          "date_formats": "Formati datuma",
          "en": "Engleski",
          "de": "Njemački",
          "hr": "Hrvatski",
          "language": "Jezik",
          "account_successfully_updated": "Vaš račun je uspješno ažuriran!",
          "dismiss": "Odbaci",
          "error_while_updating_user": "Došlo je do pogreške prilikom ažuriranja vašeg računa.",
          "profile_image": "Profilna slika",
          "background_image": "Pozadinska slika",
          "discard_image": "Odbaci sliku",
          "dropzone_text": "Ovdje ispustite slike ili pregledajte datoteke",
          "no_estates": "Nema nekretnina za prikaz!",
          "list": "Popis",
          "map": "Karta",
          "manage_presentation": "Upravljanje prezentacijom",
          "general_information": "Opće informacije",
          "additional_information": "Dodatne information",
          "description": "Opis",
          "create_estate": "Stvorite nekretninu",
          "add_new_estate": "Dodajte novu nekretninu",
          "search_text":
              "Ovdje možete pretraživati imena, adrese e-pošte i telefonske brojeve",
          "additional_filters": "Dodatni filteri",
          "number_of_estates": "Broj imanja",
          "from": "Od",
          "from_date": "Datum dolaska",
          "from_time": "Vrijeme dolaska",
          "to": "Do",
          "to_date": "Datum odlaska",
          "to_time": "Vrijeme odlaska",
          "blocked": "Blokiran",
          "individual": "Pojedinac",
          "banned": "Zabranjeno",
          "company": "Firma",
          "apply_filters": "Primijeni filtre",
          "image": "Slika",
          "name": "Ime",
          "type": "Tip",
          "users_per_page": "Korisnici po stranici",
          "scroll_to_top": "Pomaknite se na vrh",
          "allow_pets": "Dozvoljeni kućne ljubimce",
          "allow_smoking": "Dozvoljeni pušenje",
          "air_conditioning": "Klimatizacija",
          "handicap_accessible": "Pristupačno osobama s invaliditetom",
          "designated_parking_spots": "Određena parkirna mjesta",
          "outlet_type": "Vrsta izlaza",
          "house_orientation": "Orijentacija kuće",
          "accepting_payment_cards": "Prihvaćanje platnih kartica",
          "wifi": "Wifi",
          "pool": "Bazen",
          "kitchen": "Kuhinja",
          "washing_machine": "Perilica za rublje",
          "drying_machine": "Sušilica za rublje",
          "edit_presentation": "Uredi prezentaciju",
          "delete_estate": "Izbriši nekretninu",
          "delete_estate_warning_message":
              "Jeste li sigurni da želite izbrisati svoju nekretninu?",
          "cancel": "Otkaži",
          "choose_file": "Odaberite datoteku",
          "no_file": "Nema datoteke",
          "cannot_preview": "Nije moguće pregledati",
          "save_image": "Spremiti sliku",
          "banned_by_admin":
              "Administrator je izbrisao vaš korisnički račun. Za više informacija možete kontaktirati admina na admin@diplomski.com.",
          "blocked_by_admin":
              "Vaš korisnički račun je trenutno blokiran od strane administratora. Za više informacija možete kontaktirati admina na admin@diplomski.com.",
          "cant_log_in": "Došlo je do pogreške prilikom prijave.",
          "successful_login": "Uspješno ste se prijavili!",
          "old_password": "Stara lozinka",
          "new_password": "Nova lozinka",
          "repeat_password": "Ponovite lozinku",
          "type_of_customer": "Vrsta korisnika",
          "password": "Lozinka",
          "delete_account_warning_message":
              "Jeste li sigurni da želite izbrisati svoj račun? Vaši će podaci biti trajno izgubljeni!",
          "customers": "Korisnici",
          "sign_up": "Prijavite se",
          "have_account_login_here": "Već imate račun? Prijavite se ovdje.",
          "cant_register":
              "Došlo je do problema prilikom pokušaja kreiranja vašeg računa. Pokušajte ponovno kasnije.",
          "account_successfully_created":
              "Vaš račun je uspješno kreiran!",
          "keep_me_logged_in": "Zadrži me prijavljenim.",
          "dont_have_account_register_here":
              "Nemate račun? Prijavite se ovdje.",
          "sign_in": "Prijava",
          "sign_in_with_google": "Prijavite se s Googleom",
          "sign_in_with_facebook": "Prijavite se putem Facebooka",
          "avatar_image": "Profilna slika",
          "or": "ili",
          "email": "Email",
          "show": "Prikaži",
          "dont_show": "Nemoj prikazati",
          "slides": "Slajdovi",
          "title": "Naslov",
          "subtitle": "Podnaslov",
          "drop_image_here": "Ispustite sliku ovdje!",
          "template": "Predložak",
          "successfull_delete_account": "Uspješno ste izbrisali svoj račun!",
          "add_next_slide": "Dodaj slajd kao sljedeći",
          "delete_slide": "Izbriši slajd",
          "add_prev_slide": "Dodaj slajd kao prethodni",
          "key": "Skraćenica",
          "value": "Tekst",
          "variables": "Varijable",
          "no_elements": "Nema ništa za prikazati!",
          "position": "Pozicija",
          "title_text": "Tekst naslova",
          "title_alignment": "Poravnanje naslova",
          "top-left": "Gore lijevo",
          "top-center": "Gore sredina",
          "top-right": "Gore desno",
          "center": "Sredina",
          "links": "Poveznice",
          "link": "Poveznica",
          "links_text": "Tekst poveznice",
          "links_url": "URL poveznice",
          "background": "Pozadina",
          "images": "Slike",
          "open_gallery": "Otvori galeriju",
          "text": "Tekst",
          "description_text": "Tekst opisa",
          "add_category": "Dodaj kategoriju",
          "name_en": "Ime na englskom",
          "name_de": "Ime na njemačkom",
          "name_hr": "Ime na hrvatskom",
          "title_en": "Naslov na engleskom",
          "title_de": "Naslov na njemačkom",
          "title_hr": "Naslov na hrvatskom",
          "description_en": "Opis na engleskom",
          "description_de": "Opis na njemačkom",
          "description_hr": "Opis na hrvatskom",
          "guests": "Gosti",
          "set_date": "Postavi datum",
          "set_time": "Postavi vrijeme",
          "titles": "Naslovi",
          "cant_obtain_estates": "Došlo je do pogreške prilikom pokušaja dobivanja vaših nekretnina. Molimo pokušajte ponovo kasnije.",
          "cant_obtain_categories": "Došlo je do pogreške prilikom pokušaja dobivanja vaših kategorija. Molimo pokušajte ponovo kasnije.",
          "cant_obtain_elements": "Došlo je do pogreške prilikom pokušaja preuzimanja vaših stavki. Pokušajte ponovno kasnije.",
          "must_save_or_cancel_changes": "Prije odlaska na drugu stavku morate spremiti ili poništiti sve promjene.",
          "create_element": "Stvori stavku",
          "delete_element": "Izbriši stavku",
          "update_element": "Ažuriraj stavku",
          "passwords_do_not_match": "Lozinke se ne podudaraju.",
          "fill_all_requested_fields": "Ispunite sva tražena polja kako biste nastavili s postupkom registracije.",
          "old_password_does_not_match": "Unijeli ste krivu staru lozinku!",
          "error_while_updating_password": "Došlo je do pogreške prilikom ažuriranja vaše lozinke.",
          "successfull_changed_password": "Vaša lozinka je uspješno ažurirana.",
          "error_while_gathering_your_data": "Došlo je do pogreške prilikom prikupljanja vaših podataka.",
          "error_while_deleting_account": "Došlo je do pogreške prilikom brisanja vašeg računa. Molimo pokušajte ponovo kasnije.",
          "complete": "Potpun",
          "compact": "Kompaktan",
          "minimal": "Minimalan",
          "entry_fee": "Ulaznica",
          "minimal_age": "Minimalna dob",
          "monday": "Ponedjeljak",
          "tuesday": "Utorak",
          "wednesday": "Srijeda",
          "thursday": "Četvrtak",
          "friday": "Petak",
          "saturday": "Subota",
          "sunday": "Nedjelja",
          "manage_category": "Upravljaj kategorijom",
          "manage_elements": "Upravljanje stavkama",
          "show_elements": "Prikaži stavku",
          "show_category": "Prikaži kategoriju",
          "ban_user_text_1": "Jeste li sigurni da želite zabraniti ",
          "ban_user_text_2": "korištenje aplikacije? Zabrana korištenja aplikacije bilo kojem korisniku je trajna i izbrisat će njegove podatke iz baze podataka!",
          "working_hours": "Radni sati",
          "opening_hour": "Vrijeme otvaranja",
          "closing_hour": "Vrijeme zatvaranja",
          "delete_element_warning_message": "Jeste li sigurni da želite izbrisati svoj element?",
          "first_column_must_be_filled": "Kako biste nastavili sa spremanjem, morate unijeti sve vrijednosti u prvi (lijevi) stupac!",
          "new_password_too_short": "Nova lozinka je prekratka! Mora imati najmanje 8 znakova.",
          "all_general_info_has_to_be_filled": "Sva polja \"Opće informacije\" moraju biti popunjena!",
          "all_guest_info_has_to_be_filled": "Svaki kreirani red u sekciji \"Gosti\" mora biti popunjen!",
          "you_must_enter_all_names": "Za nastavak morate unijeti sva imena!",
          "cannot_update_estate": "Došlo je do pogreške prilikom ažuriranja nekretnina.",
          "estate_successfully_updated": "Imanje je uspješno ažurirano.",
          "category_successfully_updated": "Kategorija je uspješno ažurirana!",
          "error_while_updating_category": "Došlo je do pogreške prilikom ažuriranja vaše kategorije.",
          "category_successfully_created": "Kategorija je uspješno kreirana!",
          "error_while_creating_category": "Došlo je do pogreške prilikom izrade vaše kategorije.",
          "delete_category": "Izbriši kategoriju",
          "cannot_create_estate": "Došlo je do pogreške prilikom izrade vaše nekretnine.",
          "estate_successfully_created": "Vaša nekretnina je uspješno kreirana.",
          "pick_file": "Odaberite datoteku",
          "estate_successfully_deleted": "Nekretnina uspješno izbrisana!",
          "error_while_deleting_estate": "Došlo je do pogreške prilikom brisanja vaše nekretnine.",
          "error_while_deleting_category": "Došlo je do pogreške prilikom brisanja vaše kategorije.",
          "category_successfully_deleted": "Kategorija je uspješno izbrisana!",
          "error_while_updating_element": "Došlo je do pogreške prilikom ažuriranja vaše stavke.",
          "element_successfully_updated": "Element je uspješno ažuriran!",
          "error_while_deleting_element": "Došlo je do pogreške prilikom brisanja vaše stavke.",
          "element_successfully_deleted": "Element je uspješno izbrisan!",
          "error_while_creating_element": "Došlo je do pogreške prilikom stvaranja vaše stavke.",
          "element_successfully_created": "Element je uspješno stvoren!",
          "no_users_to_display": "Nema korisnika za prikaz",
        };
        return jsonHR;
    }
    return {};
  }
}
