// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr1DO0mTiEk3G7G31ir462s61f9kiZqEQ',
    appId: '1:236389351601:web:66c1f13569d93cc056a290',
    messagingSenderId: '236389351601',
    projectId: 'diplomski-rad-8bdb2',
    authDomain: 'diplomski-rad-8bdb2.firebaseapp.com',
    databaseURL: 'https://diplomski-rad-8bdb2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diplomski-rad-8bdb2.appspot.com',
    measurementId: 'G-4KSSRHL1KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDMcBpVDUxancbQzEx5mxyXGj74tvP5m8',
    appId: '1:236389351601:android:fb01a538d1b5a78856a290',
    messagingSenderId: '236389351601',
    projectId: 'diplomski-rad-8bdb2',
    databaseURL: 'https://diplomski-rad-8bdb2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diplomski-rad-8bdb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMyVgSyZvNc4oFMRf8W02b5l7nhmGrMJ0',
    appId: '1:236389351601:ios:7ab8c3561c4d8cc656a290',
    messagingSenderId: '236389351601',
    projectId: 'diplomski-rad-8bdb2',
    databaseURL: 'https://diplomski-rad-8bdb2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diplomski-rad-8bdb2.appspot.com',
    iosClientId: '236389351601-21d12mcsup5m4n4njhok0ddgkambeorf.apps.googleusercontent.com',
    iosBundleId: 'com.example.diplomskiRad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMyVgSyZvNc4oFMRf8W02b5l7nhmGrMJ0',
    appId: '1:236389351601:ios:8453b552c1522b2656a290',
    messagingSenderId: '236389351601',
    projectId: 'diplomski-rad-8bdb2',
    databaseURL: 'https://diplomski-rad-8bdb2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diplomski-rad-8bdb2.appspot.com',
    iosClientId: '236389351601-g0c969v9oksjqep23155fbpljtldttvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.diplomskiRad.RunnerTests',
  );
}
